# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/favicon.png"

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy              = "default"

[footer]
    since      = 2019
    customText = ""

[dateFormat]
    published   = ":date_full"
    lastUpdated = ":date_full"

[sidebar]
    emoji    = "ğŸ°"
    subtitle = "ì•ˆë…•í•˜ì„¸ìš”! ë°±ì—”ë“œ ê°œë°œìë¡œ ë¨¹ê³ ì‚´ê³  ìˆëŠ” cake-monotone ì…ë‹ˆë‹¤. ë‹¬ì½¤í•œ ì¼€ì´í¬ì²˜ëŸ¼ ì¢‹ì€ í•˜ë£¨ ë³´ë‚´ì„¸ìš”!"
    avatar   = "img/avatar.jpg"

[article]
    headingAnchor = false 
    math          = true
    readingTime   = true

    [article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } }
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

## Comments
[comments]
    enabled  = false
    provider = "disqus"

    # See all the available configurations at https://github.com/CaiJimmy/hugo-theme-stack/blob/master/config/_default/params.toml
    # Copy the configurations you need from there and paste it here.
